#!/bin/bash
# Simple chroot script using mount namespaces.

set -e

SHELL=/bin/bash
PATH=/usr/sbin:/usr/bin:/sbin:/bin

if [[ $EUID != 0 ]]; then
    echo 'ERROR: Must be run as root' >&2
    exit 1
fi

if [[ "$1" != "--__stage2__" ]]; then
    exec unshare --ipc --mount --pid --uts --fork "$0" --__stage2__ "${@}"
fi
shift

BIND_SRC=()
BIND_DST=()
while getopts :b:Rh opt; do
    case "${opt}" in
        b)
            if [[ "${OPTARG}" =~ ^([^:]+):([^:]+)$ ]]; then
                BIND_SRC+=("${BASH_REMATCH[1]}")
                BIND_DST+=("${BASH_REMATCH[2]}")
            elif [[ "${OPTARG}" =~ ^([^:]+)$ ]]; then
                BIND_SRC+=("${BASH_REMATCH[1]}")
                BIND_DST+=("${BASH_REMATCH[1]}")
            else
                echo Invalid bind value: ${OPTARG} >&2
                exit 2
            fi
            ;;
        R)
            READONLY=1
            ;;
        h)
            echo 'USAGE: choot [options] root [cmd [args...]]' >&2
            exit 2
            ;;
        \?)
            echo "Invalid option: -${OPTARG}" >&2
            exit 2
            ;;
        :)
            echo "Option -${OPTARG} requies an argument" >&2
            exit 2
            ;;
    esac
done
shift $((OPTIND-1))

if [[ -z "$1" ]]; then
    echo 'ERROR: Missing required root parameter'
    exit 1
fi

ROOT="$(realpath "$1")"

# Mark everything as slave so we inherit changes from system
mount --make-rslave /

# Turn target into mountpoint
mount --bind "${ROOT}" "${ROOT}"

# Make read-only (if requested)
if [[ -n "${READONLY}" ]]; then
    mount --bind -o remount,ro "${ROOT}" "${ROOT}"
fi

# Mounts
mount proc "${ROOT}/proc" -t proc
mount sys "${ROOT}/sys" -t sysfs
mount tmpfs "${ROOT}/dev" -t tmpfs -o mode=755,nosuid,strictatime
mkdir "${ROOT}/dev/pts"
mount devpts "${ROOT}/dev/pts" -t devpts
mount tmpfs "${ROOT}/run" -t tmpfs -o mode=755,nosuid,nodev,strictatime

# Devices
mknod -m 666 "${ROOT}/dev/null" c 1 3
mknod -m 666 "${ROOT}/dev/zero" c 1 5
mknod -m 666 "${ROOT}/dev/full" c 1 7
mknod -m 666 "${ROOT}/dev/random" c 1 8
mknod -m 666 "${ROOT}/dev/urandom" c 1 9
mknod -m 666 "${ROOT}/dev/tty" c 5 0
mknod -m 666 "${ROOT}/dev/ptmx" c 5 2

ln -s /proc/self/fd "${ROOT}/dev/fd"
ln -s /proc/self/fd/0 "${ROOT}/dev/stdin"
ln -s /proc/self/fd/1 "${ROOT}/dev/stdout"
ln -s /proc/self/fd/2 "${ROOT}/dev/stderr"

# Bind mounts
for (( i=0; i<${#BIND_SRC[@]}; i++ )); do
    mount --bind "${BIND_SRC[$i]}" "${ROOT}/${BIND_DST[$i]}"
done

# Environment
ENV=(
    HOME=/root
    SHELL="${SHELL}"
    PATH="${PATH}"
    TERM="${TERM}"
)

# Enter the chroot
cd "${ROOT}"
mount --move "${ROOT}" /
env - "${ENV[@]}" chroot . "${@:2}"
