#!/bin/bash
# Simple chroot script using mount namespaces.

set -e

if [[ $EUID != 0 ]]; then
    echo 'ERROR: Must be run as root' >&2
    exit 1
fi

if [[ "$1" != "--__stage2__" ]]; then
    exec unshare --ipc --mount --pid --uts --fork "$0" --__stage2__ "${@}"
fi
shift

while getopts :b:Rh opt; do
    case "${opt}" in
        R)
            READONLY=1
            ;;
        h)
            echo 'USAGE: choot [options] root [cmd [args...]]' >&2
            exit 2
            ;;
        \?)
            echo "Invalid option: -${OPTARG}" >&2
            exit 2
            ;;
        :)
            echo "Option -${OPTARG} requies an argument" >&2
            exit 2
            ;;
    esac
done
shift $((OPTIND-1))

if [[ -z "$1" ]]; then
    echo 'ERROR: Missing required root parameter'
    exit 1
fi

ROOT="$(realpath "$1")"

# Mark everything as slave so we inherit changes from system
mount --make-rslave /

# Turn target into mountpoint
mount --bind "${ROOT}" "${ROOT}"

# Make read-only (if requested)
if [[ -n "${READONLY}" ]]; then
    mount --bind -o remount,ro "${ROOT}" "${ROOT}"
fi

# Mounts
mount proc "${ROOT}/proc" -t proc
mount sys "${ROOT}/sys" -t sysfs
mount tmpfs "${ROOT}/dev" -t tmpfs -o mode=755,nosuid,strictatime
mkdir "${ROOT}/dev/pts"
mount devpts "${ROOT}/dev/pts" -t devpts
mount tmpfs "${ROOT}/run" -t tmpfs -o mode=755,nosuid,nodev,strictatime

# Devices
mknod -m 666 "${ROOT}/dev/null" c 1 3
mknod -m 666 "${ROOT}/dev/zero" c 1 5
mknod -m 666 "${ROOT}/dev/full" c 1 7
mknod -m 666 "${ROOT}/dev/random" c 1 8
mknod -m 666 "${ROOT}/dev/urandom" c 1 9
mknod -m 666 "${ROOT}/dev/tty" c 5 0
mknod -m 666 "${ROOT}/dev/ptmx" c 5 2

# Enter the chroot
cd "${ROOT}"
mount --move "${ROOT}" /
chroot . "${@:2}"
