#!/usr/bin/env python3

"""Post GitHub Gists."""

from __future__ import print_function

import argparse
from collections import OrderedDict
from os.path import basename
import os
from urllib.parse import urljoin

from utils import get_userpass

import requests

GITHUB_API = os.getenv('GITHUB_API', 'https://api.github.com')


def post_gist(files, description=None, public=None, auth=None):
    data = dict(files=files)
    if description is not None:
        data['description'] = description
    if public is not None:
        data['public'] = public
    resp = requests.post(urljoin(GITHUB_API, '/gists'), json=data, auth=auth)
    resp.raise_for_status()

    return resp.json()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--description')
    parser.add_argument('-P', '--public', action='store_true')
    parser.add_argument('-u', '--user')
    parser.add_argument('file', nargs='+', type=argparse.FileType('r'))
    args = parser.parse_args()

    auth = get_userpass(args.user) if args.user else None
    files = OrderedDict(
            ((basename(f.name), {'content': f.read()}) for f in args.file))

    resp = post_gist(files, args.description, args.public, auth=auth)
    print('Created {} gist: {}'.format('public' if args.public else 'private',
                                       resp['html_url']))


if __name__ == '__main__':
    main()
